name: reviewdog
on: [pull_request]

jobs:
  lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: Check out code
        uses: actions/checkout@v4
      - name: golanci-lint
        uses: upfluence/action-golangci-lint@master
        with:
          github_token: ${{ secrets.github_token }}
